version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:17" # GitHub says 'High load times include the start of every hour'
      timezone: "Europe/Oslo"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "maven"
    directory: "/dhis-2"
    schedule:
      interval: "daily"
      time: "02:17" # GitHub says 'High load times include the start of every hour'
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "-"
